/*
 * This file was automatically generated by EvoSuite
 * Sun Sep 16 08:23:59 GMT 2018
 */

package eu.stamp.uc.atos.poc.evocrash;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import eu.stamp.uc.atos.poc.evocrash.MyObject;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MyObject_ESTest extends MyObject_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MyObject myObject0 = new MyObject();
      // Undeclared exception!
      try { 
        myObject0.unnecessaryMethod();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.Boolean cannot be cast to java.lang.String
         //
         verifyException("eu.stamp.uc.atos.poc.evocrash.MyObject", e);
      }
  }
}
