/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 07 15:24:06 CEST 2021
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class _ESTest extends _ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = "";
      String string1 = "";
      string1.equals(string0);
      string1.equals(string0);
      string0.equals(string1);
      String string2 = "";
      string1.equals(string2);
      String string3 = "6AUEy9";
      string2.equals(string3);
      String string4 = "\\i'>tc#N{_";
      String string5 = "1>9YQA$+].yyp\"";
      string5.equals(string4);
      String string6 = "";
      string2.equals(string4);
      String string7 = "D";
      string7.equals(string5);
      Object object0 = null;
      string5.equals(object0);
      String string8 = "wT$>vEo (hCvWU-Mv";
      string8.equals(string6);
      string5.equals(string0);
      string6.equals(string8);
      String string9 = "";
      string9.equals(string2);
      String string10 = "H+-#khW5oV";
      string5.equals(string10);
  }
}
